# TDD Configuration for Helios v1.0 - 100% Coverage + 100% Pass Rate

[tdd.quality_requirements]
# Coverage Requirements (Path to 100%)
unit_test_coverage = 0.95           # 95% minimum unit coverage
integration_coverage = 0.90         # 90% minimum integration coverage
e2e_coverage = 0.85                # 85% minimum E2E coverage
critical_path_coverage = 0.99       # 99% critical path coverage

# Performance Requirements (Your roadmap targets)
max_render_time_100k_ms = 3         # 100k points in 3ms
max_memory_1m_points_mb = 50        # 1M points in 50MB
min_target_fps = 60.0               # 60fps minimum
max_wasm_bundle_kb = 120            # <120KB WASM bundle

# Test Quality Requirements (100% pass rate)
mutation_test_score = 0.80          # 80% mutation survival
property_test_success = 1.00        # 100% property test success
max_flaky_test_rate = 0.00          # 0% flaky tests allowed

# Test Speed Requirements
unit_max_ms = 1                     # <1ms unit tests
integration_max_ms = 100            # <100ms integration
e2e_max_s = 5                      # <5s E2E tests

# Quality Gate Thresholds
min_code_quality_score = 0.90       # 90% code quality
max_technical_debt_ratio = 0.10     # <10% technical debt
min_documentation_coverage = 0.95   # 95% API documentation

[tdd.test_pyramid]
# Test Distribution (70/20/10 pyramid)
unit_test_percentage = 0.70         # 70% unit tests
integration_percentage = 0.20       # 20% integration tests
e2e_percentage = 0.10              # 10% E2E tests

[tdd.automation]
# Automated TDD enforcement
enforce_coverage_gates = true
enforce_performance_gates = true
enforce_mutation_testing = true
enforce_property_testing = true

# CI/CD Integration
fail_on_coverage_below_threshold = true
fail_on_performance_regression = true
fail_on_flaky_tests = true

[tdd.tools]
# Testing framework configuration
coverage_tool = "tarpaulin"
mutation_tool = "cargo-mutants"
property_testing = "proptest"
benchmarking = "criterion"
browser_testing = "wasm-bindgen-test"

[tdd.phases]
# Roadmap phase targets
[tdd.phases.phase1]
name = "Foundation (Weeks 1-4)"
coverage_target = 0.70
tests_added = 800
focus = ["Infrastructure", "Core TDD patterns", "Performance baselines"]

[tdd.phases.phase2]
name = "Performance (Weeks 5-8)"
coverage_target = 0.80
tests_added = 600
focus = ["GPU acceleration", "WASM optimization", "Benchmarking"]

[tdd.phases.phase3]
name = "Intelligence (Weeks 9-12)"
coverage_target = 0.90
tests_added = 500
focus = ["ML integration", "Property testing", "Advanced features"]

[tdd.phases.phase4]
name = "Production (Weeks 13-16)"
coverage_target = 1.00
tests_added = 300
focus = ["Enterprise features", "Accessibility", "Final validation"]
