name: TDD Quality Gates - 100% Coverage Enforcement

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  tdd-validation:
    name: TDD Cycle Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
        target: wasm32-unknown-unknown
        override: true

    # Install testing tools
    - name: Install TDD Tools
      run: |
        cargo install cargo-tarpaulin
        cargo install cargo-mutants
        cargo install wasm-pack

    # RED-GREEN-REFACTOR Validation
    - name: Validate TDD Cycle Compliance
      run: |
        # Ensure all tests pass (GREEN requirement)
        echo "🟢 GREEN: Running full test suite..."
        cargo test --all-features --workspace

        # Format and lint validation
        echo "🔧 REFACTOR: Code quality checks..."
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features --workspace -- -D warnings

    - name: Code Coverage Analysis
      run: |
        # Coverage must be >= 95% (Quality requirement)
        echo "📊 COVERAGE: Measuring test coverage..."
        cargo tarpaulin --all-features --out Xml --timeout 600 \
          --target-dir target/tarpaulin \
          --exclude-files "target/*" "tests/*" "**/tests.rs" \
          --ignore-panics --count

        # Check coverage threshold (95% requirement)
        python3 -c "
        import xml.etree.ElementTree as ET
        tree = ET.parse('cobertura.xml')
        coverage = float(tree.getroot().attrib['line-rate']) * 100
        print(f'Coverage: {coverage:.2f}%')
        assert coverage >= 95.0, f'Coverage {coverage:.2f}% below 95% requirement'
        print('✅ Coverage requirement met!')
        "

    - name: Mutation Testing Quality Gate
      run: |
        # Mutation testing score >= 80% (Test quality requirement)
        echo "🧬 MUTATION: Testing test quality..."
        timeout 1800 cargo mutants --timeout 120 --check

    - name: WASM Build Validation
      run: |
        # WASM builds must succeed (Integration requirement)
        echo "🌐 WASM: Building for web targets..."
        cargo build --target wasm32-unknown-unknown --all-features

        # Bundle size validation
        wasm-pack build helios-core --target web --out-dir pkg

        # Check bundle size (<120KB requirement)
        BUNDLE_SIZE=$(wc -c < helios-core/pkg/leptos_helios_bg.wasm)
        BUNDLE_KB=$((BUNDLE_SIZE / 1024))
        echo "WASM bundle size: ${BUNDLE_KB}KB"

        if [ $BUNDLE_KB -gt 120 ]; then
          echo "❌ WASM bundle too large: ${BUNDLE_KB}KB > 120KB"
          exit 1
        fi

        echo "✅ WASM bundle size requirement met!"

  performance-validation:
    name: Performance Regression Detection
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run Performance Benchmarks
      run: |
        echo "⚡ PERFORMANCE: Running benchmarks..."
        cargo bench --workspace -- --output-format json | tee benchmark_results.json

        # Basic performance validation
        echo "✅ Performance benchmarks completed!"

  cross-browser-testing:
    name: Cross-Browser E2E Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: WASM + WebGPU Browser Testing
      run: |
        echo "🌐 E2E: Cross-browser testing..."

        # Test Chrome (WebGPU support)
        wasm-pack test --chrome --headless helios-core

        # Test Firefox (WebGPU support)
        wasm-pack test --firefox --headless helios-core

        echo "✅ Cross-browser testing completed!"

  coverage-report:
    name: Coverage Report Generation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install Tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate Coverage Report
      run: |
        cargo tarpaulin --all-features --out Html --timeout 600 \
          --target-dir target/tarpaulin \
          --exclude-files "target/*" "tests/*" "**/tests.rs"

    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v3
      with:
        files: ./tarpaulin-report.html
        flags: unittests
        name: helios-coverage
        fail_ci_if_error: true

  tdd-quality-summary:
    name: TDD Quality Summary
    runs-on: ubuntu-latest
    needs: [tdd-validation, performance-validation, cross-browser-testing]
    if: always()

    steps:
    - name: TDD Quality Gate Results
      run: |
        echo "🎯 TDD QUALITY GATES SUMMARY"
        echo "================================="

        if [ "${{ needs.tdd-validation.result }}" == "success" ]; then
          echo "✅ TDD Cycle Validation: PASSED"
        else
          echo "❌ TDD Cycle Validation: FAILED"
        fi

        if [ "${{ needs.performance-validation.result }}" == "success" ]; then
          echo "✅ Performance Validation: PASSED"
        else
          echo "❌ Performance Validation: FAILED"
        fi

        if [ "${{ needs.cross-browser-testing.result }}" == "success" ]; then
          echo "✅ Cross-Browser Testing: PASSED"
        else
          echo "❌ Cross-Browser Testing: FAILED"
        fi

        echo "================================="

        # Fail if any quality gate failed
        if [ "${{ needs.tdd-validation.result }}" != "success" ] || \
           [ "${{ needs.performance-validation.result }}" != "success" ] || \
           [ "${{ needs.cross-browser-testing.result }}" != "success" ]; then
          echo "❌ TDD Quality Gates: FAILED"
          exit 1
        fi

        echo "🎉 TDD Quality Gates: ALL PASSED"
        echo "Ready for v1.0 release! 🚀"
